---
title: "Arbeidskrav våren 2022"
author:
- Kevin Ha
- Ola Andre Olofsson
- Ann Elisabeth Jacobsen
- Heidi Marie Rolfsnes
subtitle: MSB106, Anvendt by- og regionaløkonomi
output:
  pdf_document: default
  html_notebook: default
  html_document:
    df_print: paged
lang: no-NB
---

```{r setup, include=FALSE}
suppressPackageStartupMessages({
  library(readr)
  library(ggplot2)
  library(knitr)
  library(viridis)
  library(tidyverse)
  })
knitr::opts_chunk$set(echo=FALSE, include = TRUE)
```

# Innlesing av .csv filer

```{r csv_filer}
syssel_arb <- read_csv("Data/syssel_arb.csv", show_col_types = FALSE)
hld_arb <- read_csv("Data/hld_arb.csv", show_col_types = FALSE)
sun_arb <- read_csv("Data/sun_arb.csv", show_col_types = FALSE)
har_arb <- read_csv("Data/har_arb.csv", show_col_types = FALSE)
syssel_bos <- read_csv("Data/syssel_bos.csv", show_col_types = FALSE)
hld_bos <- read_csv("Data/hld_bos.csv", show_col_types = FALSE)
sun_bos <- read_csv("Data/sun_bos.csv", show_col_types = FALSE)
har_bos <- read_csv("Data/har_bos.csv", show_col_types = FALSE)
```

# 1 Sysselsetting I Ulike Næringer, Etter Arbeidssted (Modeller Ferdig??)

## Haugalandet

```{r Arbeidssted_Haugalandet_1}
hld_arb %>% 
  ggplot(mapping = aes(x = År, y = Totalt)) +
  geom_line() +
  labs(title = "Haugalandet")+
  ylab("Antall ansatte i  \n alle næringer") +
  theme(axis.title.y = element_text(angle=0))+
  scale_x_continuous(breaks = seq(2008, 2020, by = 1))
```

```{r Arbeidssted_Haugalandet_2}
syssel_arb %>% 
  filter(knr %in% c(1106, 1135, 1145, 1146, 1149, 1151, 1160)) %>% 
  ggplot(mapping = aes(x = as.Date(paste0(aar, "-01-01")), y = `Alle Næringer`, (angle=0))) +
  scale_color_viridis(discrete = TRUE, option = "A") +
  geom_line(aes(group = knavn, colour = knavn)) +
  scale_size_manual(values = c(seq(2.0, 2, by = -0.1))) +
  geom_hline(yintercept = 0) +
  labs(title = "Haugalandet", x = "År", y = "Antall ansatte i  \n alle næringer") +
  theme(axis.title.y = element_text(angle=0))+
  theme(legend.position = 'bottom')
```

```{r hld_arb_long}
hld_arb_long <- syssel_arb %>%
  pivot_longer(
    cols = `Jordbruk, Skogbrug og Fiske`:Uoppgitt,
    names_to = "Næring",
    values_to = "Ansatte")
```


```{r Næringsfordeling_og_Utvikling_Haugelandet_3_Største_Arbeidssted}
hld_arb_long %>% 
  filter(knavn %in% c("Haugesund", "Karmøy", "Vindafjord")) %>% 
  filter(Næring %in% c("Industri", "Helse- og Sosialtjenester", "Finansiering og Forsikring", "Elektrisitet, Vann og Renovasjon", "Bygge- og Anleggsvirksomhet", "Jordbruk, Skogbrug og Fiske")) %>% 
  ggplot(mapping = aes(x = as.Date(paste0(aar, "-01-01")), y = Ansatte)) +
  scale_color_viridis(discrete = TRUE, option = "A") +
  labs(title = "Haugalandet: Haugesund, Karmøy og Vindafjord", x = "År", y = "Antall ansatte") +
  geom_line(mapping = aes(group = Næring, colour = Næring)) +
  facet_wrap(facets = ~ knavn, scales = "free_y", ncol = 3) +
  theme(legend.position = 'bottom')
```

```{r Næringsfordeling_og_Utvikling_Haugelandet_4_Minste_Arbeidssted}
hld_arb_long %>% 
  filter(knavn %in% c("Bokn", "Sauda", "Tysvær", "Utsira")) %>% 
  filter(Næring %in% c("Industri", "Helse- og Sosialtjenester", "Finansiering og Forsikring", "Elektrisitet, Vann og Renovasjon", "Bygge- og Anleggsvirksomhet", "Jordbruk, Skogbrug og Fiske")) %>% 
  ggplot(mapping = aes(x = as.Date(paste0(aar, "-01-01")), y = Ansatte)) +
  scale_color_viridis(discrete = TRUE, option = "A") +
  labs(title = "Haugalandet: Bokn, Sauda, Tysvær og Utsira", x = "År", y = "Antall ansatte") +
  geom_line(mapping = aes(group = Næring, colour = Næring)) +
  facet_wrap(facets = ~ knavn, scales = "free_y", ncol = 4) +
  theme(legend.position = 'bottom')
```

```{r Haugesund}
syssel_arb %>%
  filter(knr == 1106) %>%
 ggplot(mapping = aes(x = aar, y = `Alle Næringer`)) +
  geom_line() +
  labs(title = "Haugesund", x = "År", y = "Antall ansatte i  \n alle næringer") +
  theme(axis.title.y = element_text(angle=0))+
  scale_x_continuous(breaks = seq(2008, 2020, by = 1)) +
  coord_cartesian(ylim = c(20852, 22190), xlim = c())
```

```{r Sauda}
syssel_arb %>%
  filter(knr == 1135) %>%
 ggplot(mapping = aes(x = aar, y = `Alle Næringer`)) +
  geom_line() +
  labs(title = "Sauda", x = "År", y = "Antall ansatte i  \n alle næringer") +
  theme(axis.title.y = element_text(angle=0))+
  scale_x_continuous(breaks = seq(2008, 2020, by = 1)) +
  coord_cartesian(ylim = c(1937, 2180), xlim = c())
```

```{r Bokn}
syssel_arb %>%
  filter(knr == 1145) %>%
 ggplot(mapping = aes(x = aar, y = `Alle Næringer`)) +
  geom_line() +
  labs(title = "Bokn", x = "År", y = "Antall ansatte i  \n alle næringer") +
  theme(axis.title.y = element_text(angle=0))+ 
  scale_x_continuous(breaks = seq(2008, 2020, by = 1)) +
  coord_cartesian(ylim = c(291, 327), xlim = c())
```

```{r Tysvær}
syssel_arb %>%
  filter(knr == 1146) %>%
 ggplot(mapping = aes(x = aar, y = `Alle Næringer`)) +
  geom_line() +
  labs(title = "Tysvær", x = "År", y = "Antall ansatte i  \n alle næringer") +
  theme(axis.title.y = element_text(angle=0))+ 
  scale_x_continuous(breaks = seq(2008, 2020, by = 1)) +
  coord_cartesian(ylim = c(4048, 4773), xlim = c())
```

```{r Karmøy}
syssel_arb %>%
  filter(knr == 1149) %>%
 ggplot(mapping = aes(x = aar, y = `Alle Næringer`)) +
  geom_line() +
  labs(title = "Karmøy", x = "År", y = "Antall ansatte i  \n alle næringer") +
  theme(axis.title.y = element_text(angle=0))+ 
  scale_x_continuous(breaks = seq(2008, 2020, by = 1)) +
  coord_cartesian(ylim = c(14591, 16059), xlim = c())
```

```{r Utsira}
syssel_arb %>%
  filter(knr == 1151) %>%
 ggplot(mapping = aes(x = aar, y = `Alle Næringer`)) +
  geom_line() +
  labs(title = "Utsira", x = "År", y = "Antall ansatte i  \n alle næringer") +
  theme(axis.title.y = element_text(angle=0))+ 
  scale_x_continuous(breaks = seq(2008, 2020, by = 1)) +
  coord_cartesian(ylim = c(88, 114), xlim = c())
```

```{r Vindafjord}
syssel_arb %>%
  filter(knr == 1160) %>%
 ggplot(mapping = aes(x = aar, y = `Alle Næringer`)) +
  geom_line() +
  labs(title = "Vindafjord", x = "År", y = "Antall ansatte i  \n alle næringer") +
  theme(axis.title.y = element_text(angle=0))+ 
  scale_x_continuous(breaks = seq(2008, 2020, by = 1)) +
  coord_cartesian(ylim = c(4422, 5037), xlim = c())
```

## Sunnhordland

Så gjer vi det samme for *Sunnhordland*

```{r}
sun_arb %>% 
  ggplot(mapping = aes(x = År, y = Totalt)) +
  geom_line() +
  labs(title = "Sunnhordaland", x = "År", y = "Antall ansatte i  \n alle næringer") +
  theme(axis.title.y = element_text(angle=0))+ 
  scale_x_continuous(breaks = seq(2008, 2020, by = 1))
```


```{r Arbeidssted_Sunnhordland}
syssel_arb %>% 
  filter(knr %in% c(4611, 4612, 4613, 4614, 4615, 4616, 4617)) %>% 
  ggplot(mapping = aes(x = aar, y = `Alle Næringer`)) +
  scale_color_viridis(discrete = TRUE, option = "A") +
  geom_line(aes(group = knavn, colour = knavn)) +
  scale_size_manual(values = c(seq(2.0, 2, by = -0.1))) +
  geom_hline(yintercept = 0) +
  scale_x_continuous(breaks = seq(2008, 2020, by = 1)) +
   labs(title = "Sunnhordland", x = "År") +
  theme(legend.position = 'bottom')
```

```{r sun_arb_long}
sun_arb_long <- syssel_arb %>%
  pivot_longer(
    cols = `Jordbruk, Skogbrug og Fiske`:Uoppgitt,
    names_to = "Næring",
    values_to = "Ansatte")
```

```{r Næringsfordeling_og_Utvikling_Sunnhordland_3_Største_Arbeidssted}
sun_arb_long %>% 
  filter(knavn %in% c("Bømlo", "Stord", "Kvinnherad")) %>% 
  filter(Næring %in% c("Industri", "Helse- og Sosialtjenester", "Finansiering og Forsikring", "Elektrisitet, Vann og Renovasjon", "Bygge- og Anleggsvirksomhet", "Jordbruk, Skogbrug og Fiske")) %>% 
  ggplot(mapping = aes(x = as.Date(paste0(aar, "-01-01")), y = Ansatte)) +
  scale_color_viridis(discrete = TRUE, option = "A") +
  labs(title = "Sunnhordland: Bømlo, Kvinnherad og Stord", x = "År", y = "Antall ansatte") +
  geom_line(mapping = aes(group = Næring, colour = Næring)) +
  facet_wrap(facets = ~ knavn, scales = "free_y", ncol = 3) +
  theme(legend.position = 'bottom')
```

```{r Næringsfordeling_og_Utvikling_Sunnhordland_4_Minste_Arbeidssted}
sun_arb_long %>% 
  filter(knavn %in% c("Etne", "Sveio", "Fitjar", "Tysnes")) %>% 
  filter(Næring %in% c("Industri", "Helse- og Sosialtjenester", "Finansiering og Forsikring", "Elektrisitet, Vann og Renovasjon", "Bygge- og Anleggsvirksomhet", "Jordbruk, Skogbrug og Fiske")) %>% 
  ggplot(mapping = aes(x = as.Date(paste0(aar, "-01-01")), y = Ansatte)) +
  scale_color_viridis(discrete = TRUE, option = "A") +
  labs(title = "Sunnhordland: Etne, Fitjar, Sveio og Tysnes", x = "År", y = "Antall ansatte") +
  geom_line(mapping = aes(group = Næring, colour = Næring)) +
  facet_wrap(facets = ~ knavn, scales = "free_y", ncol = 4) +
  theme(legend.position = 'bottom')
```

```{r Etne}
syssel_arb %>%
  filter(knr == 4611) %>%
 ggplot(mapping = aes(x = aar, y = `Alle Næringer`)) +
  geom_line() +
  labs(title = "Etne", x = "År") + 
  scale_x_continuous(breaks = seq(2008, 2020, by = 1)) +
  coord_cartesian(ylim = c(1613, 1775), xlim = c())
```

```{r Sveio}
syssel_arb %>%
  filter(knr == 4612) %>%
 ggplot(mapping = aes(x = aar, y = `Alle Næringer`)) +
  geom_line() +
  labs(title = "Sveio", x = "År") + 
  scale_x_continuous(breaks = seq(2008, 2020, by = 1)) +
  coord_cartesian(ylim = c(1357, 1523), xlim = c())
```

```{r Bømlo}
syssel_arb %>%
  filter(knr == 4613) %>%
 ggplot(mapping = aes(x = aar, y = `Alle Næringer`)) +
  geom_line() +
  labs(title = "Bømlo", x = "År") + 
  scale_x_continuous(breaks = seq(2008, 2020, by = 1)) +
  coord_cartesian(ylim = c(4662, 4890), xlim = c())
```

```{r Stord}
syssel_arb %>%
  filter(knr == 4614) %>%
 ggplot(mapping = aes(x = aar, y = `Alle Næringer`)) +
  geom_line() +
  labs(title = "Stord", x = "År") + 
  scale_x_continuous(breaks = seq(2008, 2020, by = 1)) +
  coord_cartesian(ylim = c(9161, 9938), xlim = c())
```

```{r Fitjar}
syssel_arb %>%
  filter(knr == 4615) %>%
 ggplot(mapping = aes(x = aar, y = `Alle Næringer`)) +
  geom_line() +
  labs(title = "Fitjar", x = "År") + 
  scale_x_continuous(breaks = seq(2008, 2020, by = 1)) +
  coord_cartesian(ylim = c(1085, 1259), xlim = c())
```

```{r Tysnes}
syssel_arb %>%
  filter(knr == 4616) %>%
 ggplot(mapping = aes(x = aar, y = `Alle Næringer`)) +
  geom_line() +
  labs(title = "Tysnes", x = "År") + 
  scale_x_continuous(breaks = seq(2008, 2020, by = 1)) +
  coord_cartesian(ylim = c(989, 1188), xlim = c())
```

```{r Kvinnherad}
syssel_arb %>%
  filter(knr == 4617) %>%
 ggplot(mapping = aes(x = aar, y = `Alle Næringer`)) +
  geom_line() +
  labs(title = "Kvinnherad", x = "År") + 
  scale_x_continuous(breaks = seq(2008, 2020, by = 1)) +
  coord_cartesian(ylim = c(5472, 6084), xlim = c())
```

## Hardanger

Til slutt må vi gjere det samme med *Hardanger*

```{r Arbeidssted_Hardanger_1}
har_arb %>% 
  ggplot(mapping = aes(x = År, y = Totalt)) +
  geom_line() +
  labs(title = "Hardanger", y= "Alle Næringer") + 
  scale_x_continuous(breaks = seq(2008, 2020, by = 1))
```

```{r Arbeidssted_Hardanger_2}
syssel_arb %>% 
  filter(knr %in% c(4618, 1228)) %>% 
  ggplot(mapping = aes(x = aar, y = `Alle Næringer`)) +
  scale_color_viridis(discrete = TRUE, option = "A") +
  geom_line(aes(group = knavn, colour = knavn)) +
  scale_color_manual(values=c('#111111','#054987')) +
  scale_size_manual(values = c(seq(2.0, 2, by = -0.1))) +
  geom_hline(yintercept = 0) +
  scale_x_continuous(breaks = seq(2008, 2020, by = 1)) +
   labs(title = "Hardanger", x = "År") +
  theme(legend.position = 'bottom')
```

```{r har_arb_long}
har_arb_long <- syssel_arb %>%
  pivot_longer(
    cols = `Jordbruk, Skogbrug og Fiske`:Uoppgitt,
    names_to = "Næring",
    values_to = "Ansatte")
```

```{r Næringsfordeling_og_Utvikling_Hardanger_Arbeidssted}
har_arb_long %>% 
  filter(knavn %in% c("Odda", "Ullensvang")) %>% 
  filter(Næring %in% c("Industri", "Helse- og Sosialtjenester", "Finansiering og Forsikring", "Elektrisitet, Vann og Renovasjon", "Bygge- og Anleggsvirksomhet", "Jordbruk, Skogbrug og Fiske")) %>% 
  ggplot(mapping = aes(x = as.Date(paste0(aar, "-01-01")), y = Ansatte)) +
  scale_color_viridis(discrete = TRUE, option = "A") +
  labs(title = "Hardanger: Odda, Ullensvang", x = "År", y = "Antall ansatte") +
  geom_line(mapping = aes(group = Næring, colour = Næring)) +
  facet_wrap(facets = ~ knavn, scales = "free_y", ncol = 3) +
  theme(legend.position = 'bottom')
```

```{r Odda}
syssel_arb %>%
  filter(knr == 1228) %>%
 ggplot(mapping = aes(x = aar, y = `Alle Næringer`)) +
  geom_line() +
  labs(title = "Odda", x = "År") + 
  scale_x_continuous(breaks = seq(2008, 2020, by = 1)) +
  coord_cartesian(ylim = c(3489, 3740), xlim = c())
```

```{r Ullensvang}
syssel_arb %>%
  filter(knr == 4618) %>%
 ggplot(mapping = aes(x = aar, y = `Alle Næringer`)) +
  geom_line() +
  labs(title = "Ullensvang", x = "År") + 
  scale_x_continuous(breaks = seq(2008, 2020, by = 1)) +
  coord_cartesian(ylim = c(1235, 5291), xlim = c())
```

# 3 Sysselsetting I Ulike Næringer, Etter Bosted (Modeller Under Arbeid)

## Haugalandet

```{r Bosted_Haugalandet_1}
hld_bos %>% 
  ggplot(mapping = aes(x = År, y = Totalt)) +
  geom_line() +
  labs(title = "Haugalandet")+
  ylab("Antall ansatte i  \n alle næringer") +
  theme(axis.title.y = element_text(angle=0))+
  scale_x_continuous(breaks = seq(2008, 2020, by = 1))
```

```{r Bosted_Haugalandet_2}
syssel_bos %>% 
  filter(knr %in% c(1106, 1135, 1145, 1146, 1149, 1151, 1160)) %>% 
  ggplot(mapping = aes(x = as.Date(paste0(aar, "-01-01")), y = `Alle Næringer`, (angle=0))) +
  scale_color_viridis(discrete = TRUE, option = "A") +
  geom_line(aes(group = knavn, colour = knavn)) +
  scale_size_manual(values = c(seq(2.0, 2, by = -0.1))) +
  geom_hline(yintercept = 0) +
  labs(title = "Haugalandet", x = "År", y = "Antall ansatte i  \n alle næringer") +
  theme(axis.title.y = element_text(angle=0))+
  theme(legend.position = 'bottom')
```

```{r hld_bos_long}
hld_bos_long <- syssel_bos %>%
  pivot_longer(
    cols = `Jordbruk, Skogbrug og Fiske`:Uoppgitt,
    names_to = "Næring",
    values_to = "Ansatte")
```

```{r Næringsfordeling_og_Utvikling_Haugelandet_3_Største_Bosted}
hld_bos_long %>% 
  filter(knavn %in% c("Haugesund", "Karmøy", "Vindafjord")) %>% 
  filter(Næring %in% c("Industri", "Helse- og Sosialtjenester", "Finansiering og Forsikring", "Elektrisitet, Vann og Renovasjon", "Bygge- og Anleggsvirksomhet", "Jordbruk, Skogbrug og Fiske")) %>% 
  ggplot(mapping = aes(x = as.Date(paste0(aar, "-01-01")), y = Ansatte)) +
  scale_color_viridis(discrete = TRUE, option = "A") +
  labs(title = "Haugalandet: Haugesund, Karmøy og Vindafjord", x = "År", y = "Antall ansatte") +
  geom_line(mapping = aes(group = Næring, colour = Næring)) +
  facet_wrap(facets = ~ knavn, scales = "free_y", ncol = 3) +
  theme(legend.position = 'bottom')
```

```{r Næringsfordeling_og_Utvikling_Haugelandet_4_Minste_Bosted}
hld_bos_long %>% 
  filter(knavn %in% c("Bokn", "Sauda", "Tysvær", "Utsira")) %>% 
  filter(Næring %in% c("Industri", "Helse- og Sosialtjenester", "Finansiering og Forsikring", "Elektrisitet, Vann og Renovasjon", "Bygge- og Anleggsvirksomhet", "Jordbruk, Skogbrug og Fiske")) %>% 
  ggplot(mapping = aes(x = as.Date(paste0(aar, "-01-01")), y = Ansatte)) +
  scale_color_viridis(discrete = TRUE, option = "A") +
  labs(title = "Haugalandet: Bokn, Sauda, Tysvær og Utsira", x = "År", y = "Antall ansatte") +
  geom_line(mapping = aes(group = Næring, colour = Næring)) +
  facet_wrap(facets = ~ knavn, scales = "free_y", ncol = 4) +
  theme(legend.position = 'bottom')
```

## Sunnhordland

```{r Bosted_Sunnhordland_1}
sun_bos %>% 
  ggplot(mapping = aes(x = År, y = Totalt)) +
  geom_line() +
  labs(title = "Sunnhordaland", x = "År", y = "Antall ansatte i  \n alle næringer") +
  theme(axis.title.y = element_text(angle=0))+ 
  scale_x_continuous(breaks = seq(2008, 2020, by = 1))
```


```{r Bosted_Sunnhordland_2}
syssel_bos %>% 
  filter(knr %in% c(4611, 4612, 4613, 4614, 4615, 4616, 4617)) %>% 
  ggplot(mapping = aes(x = aar, y = `Alle Næringer`)) +
  scale_color_viridis(discrete = TRUE, option = "A") +
  geom_line(aes(group = knavn, colour = knavn)) +
  scale_size_manual(values = c(seq(2.0, 2, by = -0.1))) +
  geom_hline(yintercept = 0) +
  scale_x_continuous(breaks = seq(2008, 2020, by = 1)) +
   labs(title = "Sunnhordland", x = "År") +
  theme(legend.position = 'bottom')
```

```{r sun_bos_long}
sun_bos_long <- syssel_bos %>%
  pivot_longer(
    cols = `Jordbruk, Skogbrug og Fiske`:Uoppgitt,
    names_to = "Næring",
    values_to = "Ansatte")
```

```{r Næringsfordeling_og_Utvikling_Sunnhordland_3_Største_Bosted}
sun_bos_long %>% 
  filter(knavn %in% c("Bømlo", "Stord", "Kvinnherad")) %>% 
  filter(Næring %in% c("Industri", "Helse- og Sosialtjenester", "Finansiering og Forsikring", "Elektrisitet, Vann og Renovasjon", "Bygge- og Anleggsvirksomhet", "Jordbruk, Skogbrug og Fiske")) %>% 
  ggplot(mapping = aes(x = as.Date(paste0(aar, "-01-01")), y = Ansatte)) +
  scale_color_viridis(discrete = TRUE, option = "A") +
  labs(title = "Sunnhordland: Bømlo, Kvinnherad og Stord", x = "År", y = "Antall ansatte") +
  geom_line(mapping = aes(group = Næring, colour = Næring)) +
  facet_wrap(facets = ~ knavn, scales = "free_y", ncol = 3) +
  theme(legend.position = 'bottom')
```

```{r Næringsfordeling_og_Utvikling_Sunnhordland_4_Minste_Bosted}
sun_bos_long %>% 
  filter(knavn %in% c("Etne", "Sveio", "Fitjar", "Tysnes")) %>% 
  filter(Næring %in% c("Industri", "Helse- og Sosialtjenester", "Finansiering og Forsikring", "Elektrisitet, Vann og Renovasjon", "Bygge- og Anleggsvirksomhet", "Jordbruk, Skogbrug og Fiske")) %>% 
  ggplot(mapping = aes(x = as.Date(paste0(aar, "-01-01")), y = Ansatte)) +
  scale_color_viridis(discrete = TRUE, option = "A") +
  labs(title = "Sunnhordland: Etne, Fitjar, Sveio og Tysnes", x = "År", y = "Antall ansatte") +
  geom_line(mapping = aes(group = Næring, colour = Næring)) +
  facet_wrap(facets = ~ knavn, scales = "free_y", ncol = 4) +
  theme(legend.position = 'bottom')
```

## Hardanger

```{r Bosted_Hardanger_1}
har_bos %>% 
  ggplot(mapping = aes(x = År, y = Totalt)) +
  geom_line() +
  labs(title = "Hardanger", y= "Alle Næringer") + 
  scale_x_continuous(breaks = seq(2008, 2020, by = 1))
```

```{r Bosted_Hardanger_2}
syssel_bos %>% 
  filter(knr %in% c(4618, 1228)) %>% 
  ggplot(mapping = aes(x = aar, y = `Alle Næringer`)) +
  scale_color_viridis(discrete = TRUE, option = "A") +
  geom_line(aes(group = knavn, colour = knavn)) +
  scale_color_manual(values=c('#111111','#054987')) +
  scale_size_manual(values = c(seq(2.0, 2, by = -0.1))) +
  geom_hline(yintercept = 0) +
  scale_x_continuous(breaks = seq(2008, 2020, by = 1)) +
   labs(title = "Hardanger", x = "År") +
  theme(legend.position = 'bottom')
```

```{r har_bos_long}
har_bos_long <- syssel_bos %>%
  pivot_longer(
    cols = `Jordbruk, Skogbrug og Fiske`:Uoppgitt,
    names_to = "Næring",
    values_to = "Ansatte")
```

```{r Næringsfordeling_og_Utvikling_Hardanger_Bosted}
har_bos_long %>% 
  filter(knavn %in% c("Odda", "Ullensvang")) %>% 
  filter(Næring %in% c("Industri", "Helse- og Sosialtjenester", "Finansiering og Forsikring", "Elektrisitet, Vann og Renovasjon", "Bygge- og Anleggsvirksomhet", "Jordbruk, Skogbrug og Fiske")) %>% 
  ggplot(mapping = aes(x = as.Date(paste0(aar, "-01-01")), y = Ansatte)) +
  scale_color_viridis(discrete = TRUE, option = "A") +
  labs(title = "Hardanger: Odda, Ullensvang", x = "År", y = "Antall ansatte") +
  geom_line(mapping = aes(group = Næring, colour = Næring)) +
  facet_wrap(facets = ~ knavn, scales = "free_y", ncol = 3) +
  theme(legend.position = 'bottom')
```


-
```{r siste}
# Siste
```

-
