---
title: "Datasamling"
output: html_notebook 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, include = FALSE)
suppressPackageStartupMessages({
library(PxWebApiData)
library(tidyverse)
library(lubridate)
})
```

```{r knr}
# Vector med relevante kommunenummer
load("knr.Rdata")
```

```{r Moenster}
# Legger inn regex mønster
moenster <- '\\s*\\([\\d\\s-]*\\d*\\)\\s*$'
```

# 1a. Sysselsatte Etter Arbeidssted (Kevin & Ola A.)

```{r}
# Henter her inn data via API og inkluderer alle kommunenumre
syssel_arb <- ApiData(
  urlToData = "07984",
  Region = list("vs:KommunerS", c(
          "1106",
          "1135",
          "1145",
          "1146",
          "1149",
          "1151",
          "1160",
          "4611",
          "4612",
          "4613",
          "4614",
          "4615",
          "4616",
          "4617",
          "4618",
          "1211",
          "1216",
          "1219",
          "1221",
          "1222",
          "1223",
          "1224",
          "1227",
          "1228",
          "1231")),
  ContentsCode = "SysselsatteArb",
  NACE2007 = TRUE,
  Alder = "15-74",
  Kjonn = "0",
  Tid = c(
    as.character(2008:2020)))
```

```{r}
syssel_arb <- syssel_arb$dataset %>% 
  tibble() %>% 
  rename(
    knr = Region,
    aar = Tid
) %>% 
    mutate(knavn = syssel_arb$`07984: Sysselsatte per 4. kvartal, etter region, næring (SN2007), kjønn, alder, statistikkvariabel og år`$region)
```

```{r}
# Fjerne irrelevant kolonne som heter NAstatus
syssel_arb <- syssel_arb %>% 
  select(-NAstatus)
```

```{r}
syssel_arb <- syssel_arb %>% 
  pivot_wider(
    names_from = NACE2007,
    values_from = value)
```

```{r}
names(syssel_arb)[[1]] <- "knr"
```

```{r}
syssel_arb <- syssel_arb %>%
  filter(
    knr %in% c(1106, 1135, 1145, 1146, 1149, 1151, 1160, 1211, 4611, 1216, 4612, 1219, 4613, 1221, 4614, 1222, 4615, 1223, 4616, 1224, 4617, 1228, 1231, 4618))
```

```{r}
syssel_arb <- syssel_arb %>% 
  mutate(
    knavn = str_replace(knavn, moenster, ""))
```

```{r}
syssel_arb <- syssel_arb %>% 
  mutate(
    Kjonn = fct_recode(Kjonn,
                     "Begge Kjønn" = "0"))
```

```{r}
names(syssel_arb)[[7]] <- "Alle Næringer"
names(syssel_arb)[[8]] <- "Jordbruk, Skogbrug og Fiske"
names(syssel_arb)[[9]] <- "Bergverksdrift og Utvinning"
names(syssel_arb)[[10]] <- "Industri"
names(syssel_arb)[[11]] <- "Elektrisitet, Vann og Renovasjon"
names(syssel_arb)[[12]] <- "Bygge- og Anleggsvirksomhet"
names(syssel_arb)[[13]] <- "Varehandel, Reperasjon av Motorvogner"
names(syssel_arb)[[14]] <- "Transport og Lagring"
names(syssel_arb)[[15]] <- "Overnattings- og Servicevirksomhet"
names(syssel_arb)[[16]] <- "Informasjon og Kommunikasjon"
names(syssel_arb)[[17]] <- "Finansiering og Forsikring"
names(syssel_arb)[[18]] <- "Teknisk Tjenesteyting, Eiendomsdrift"
names(syssel_arb)[[19]] <- "Forretningsmessig Tjenesteyting"
names(syssel_arb)[[20]] <- "Off.Adm, Forsvar, Sosialforsikring"
names(syssel_arb)[[21]] <- "Undervisning"
names(syssel_arb)[[22]] <- "Helse- og Sosialtjenester"
names(syssel_arb)[[23]] <- "Personlig Tjenesteyting"
names(syssel_arb)[[24]] <- "Uoppgitt"
```

```{r removing rows with zero values}
row_sub = apply(syssel_arb, 1, function(row) all(row !=0 ))
syssel_arb[row_sub,]
```


# 1b. Sysselsatte Etter Bosted (Kevin & Ola A.)

```{r}
# Henter her inn data via API og inkluderer alle kommunenumre
syssel_bos <- ApiData(
  urlToData = "07984",
  Region = list("vs:KommunerS", c(
          "1106",
          "1135",
          "1145",
          "1146",
          "1149",
          "1151",
          "1160",
          "4611",
          "4612",
          "4613",
          "4614",
          "4615",
          "4616",
          "4617",
          "4618",
          "1211",
          "1216",
          "1219",
          "1221",
          "1222",
          "1223",
          "1224",
          "1227",
          "1228",
          "1231")),
  ContentsCode = "Sysselsatte",
  NACE2007 = TRUE,
  Alder = "15-74",
  Kjonn = "0",
  Tid = c(
    as.character(2008:2020)))
```

```{r}
syssel_bos <- syssel_bos$dataset %>% 
  tibble() %>% 
  rename(
    knr = Region,
    aar = Tid
) %>% 
    mutate(knavn = syssel_bos$`07984: Sysselsatte per 4. kvartal, etter region, næring (SN2007), kjønn, alder, statistikkvariabel og år`$region)
```

```{r}
syssel_bos <- syssel_bos %>% 
  pivot_wider(
    names_from = NACE2007,
    values_from = value)
```

```{r}
names(syssel_bos)[[1]] <- "knr"
```

```{r}
syssel_bos <- syssel_bos %>%
  filter(
    knr %in% c(1106, 1135, 1145, 1146, 1149, 1151, 1160, 1211, 4611, 1216, 4612, 1219, 4613, 1221, 4614, 1222, 4615, 1223, 4616, 1224, 4617, 1228, 1231, 4618))
```

```{r}
syssel_bos <- syssel_bos %>% 
  mutate(
    knavn = str_replace(knavn, moenster, ""))
```

```{r}
syssel_bos <- syssel_bos %>% 
  mutate(
    Kjonn = fct_recode(Kjonn,
                     "Begge Kjønn" = "0"))
```

```{r}
names(syssel_bos)[[7]] <- "Alle Næringer"
names(syssel_bos)[[8]] <- "Jordbruk, Skogbrug og Fiske"
names(syssel_bos)[[9]] <- "Bergverksdrift og Utvinning"
names(syssel_bos)[[10]] <- "Industri"
names(syssel_bos)[[11]] <- "Elektrisitet, Vann og Renovasjon"
names(syssel_bos)[[12]] <- "Bygge- og Anleggsvirksomhet"
names(syssel_bos)[[13]] <- "Varehandel, Reperasjon av Motorvogner"
names(syssel_bos)[[14]] <- "Transport og Lagring"
names(syssel_bos)[[15]] <- "Overnattings- og Servicevirksomhet"
names(syssel_bos)[[16]] <- "Informasjon og Kommunikasjon"
names(syssel_bos)[[17]] <- "Finansiering og Forsikring"
names(syssel_bos)[[18]] <- "Teknisk Tjenesteyting, Eiendomsdrift"
names(syssel_bos)[[19]] <- "Forretningsmessig Tjenesteyting"
names(syssel_bos)[[20]] <- "Off.Adm, Forsvar, Sosialforsikring"
names(syssel_bos)[[21]] <- "Undervisning"
names(syssel_bos)[[22]] <- "Helse- og Sosialtjenester"
names(syssel_bos)[[23]] <- "Personlig Tjenesteyting"
names(syssel_bos)[[24]] <- "Uoppgitt"
```


# 2. Mål for Beskrivelse av Næringsstrukturen


# 3. Sysselsetting i ulike næringer, etter arbeidsstedskommune

# 4. Pendling mellom de ulike kommunene i regionen (Heidi og Ann Elisabeth jobber videre med denne)



```{r}
Pendling_raw <- ApiData(
  urlToData = "03321",
  ArbstedKomm = c(paste0(c(1106, 1135, 1145, 1146, 
                           1149, 1151, 1160, 4611, 4612, 4613, 
                           4614, 4615, 4616, 4617, 4618),
                         ""
                         )
                  ), 
  ContentsCode = "Sysselsatte",
  Bokommuen = c(paste0(c(1106, 1135, 1145, 1146, 
                         1149, 1151, 1160, 4611, 4612, 4613, 
                         4614, 4615, 4616, 4617, 4618),
                       ""
                       )
                ),
  Tid = "2020"
  )
```

```{r}
names(Pendling_raw)[[1]] <- "desc"
```

```{r}
Pendling <- Pendling_raw$dataset %>% 
  mutate(
    NavnArbstedKomm = Pendling_raw$desc$arbeidsstedskommune,
    NavnBokommuen = Pendling_raw$desc$bostedskommune
  ) %>% 
  unite("ArbstedKomm", NavnArbstedKomm, ArbstedKomm) %>% 
  unite("Bokommuen", NavnBokommuen, Bokommuen) %>% 
  select(-ContentsCode, -Tid) %>% 
  pivot_wider(
    id_cols = ArbstedKomm,
    names_from = Bokommuen,
    values_from = value
  )
```
